export const FETCH_LOGIN = "FETCH_LOGIN";
export const SET_LOGIN = "SET_LOGIN";
export const CLEAR_LOGIN = "CLEAR_LOGIN";
export const FETCH_CHANGE_PASSWORD = "FETCH_CHANGE_PASSWORD";
export const SET_CHANGE_PASSWORD = "SET_CHANGE_PASSWORD";